#' Predict concentrations from standards fit
#' @param x A list. See details.
#' @param ignore_outliers Boolean. Should outliers be considered when
#' calculating the mean? See details.
#' @param group_cols Character vector. Columns to group by before
#' taking the mean.
#' @details The supplied list should contain two items - `fit`, generated by
#'   `qp_fit`, and `qp`, a data.frame. `qp` should contain the following:
#'   - Columns used in `fit`. Usually, this is `.log2_conc` and `.log2_abs`
#'   - Any columns in `group_cols`
#'   - If `ignore_outliers = TRUE`, `.is_outlier` will be used if supplied,
#'     or created if not.
#' @return Returns a `list` with the input fit and data.frame, with additional
#'   columns:
#'   - `.pred`: The predicted value from the provided model
#'   - `.pred_conc`: `.pred`, transformed by `conc_transform`
#'   - `.pred_conc_mean`: The mean of `.pred_conc`, sans samples where column
#'     `.is_outlier == TRUE`
#' @export
#' @importFrom rlang .data
qp_calc_conc <- function(x,
                         ignore_outliers = TRUE,
                         group_cols = c("sample_type", "index")) {
  if (is.data.frame(x)) {
    rlang::warning(c(
      "The supplied data was a data.frame, not a list",
      "Attempting to calculate a fit using supplied data.frame"
    ))
    x <- list(fit = qp_fit(x), qp = x)
  }

  qp <- x$qp
  fit <- x$fit
  check_has_cols(qp, c(group_cols, all.vars(stats::terms(fit))[-1]))
  with_predictions <- dplyr::bind_cols(qp, .pred = stats::predict(fit, qp))
  conc <- with_predictions |>
    dplyr::mutate(.pred_conc = 2^(.data$.pred) - 0.5) |>
    dplyr::group_by(dplyr::across(dplyr::any_of(group_cols)))

  if (ignore_outliers) {
    if (!".is_outlier" %in% colnames(conc)) {
      rlang::inform(
        "No colname of `.is_outlier` supplied. Calculating outliers."
      )
      conc <- dplyr::mutate(conc, .is_outlier = mark_outlier(.data$.pred))
    }
    conc <- dplyr::mutate(
      conc,
      .pred_conc_mean = mean(
        .data$.pred_conc[which(f_or_na(.data$.is_outlier))],
        na.rm = TRUE
      )
    )
  } else {
    conc <- dplyr::mutate(
      conc,
      .pred_conc_mean = mean(.data$.pred_conc, na.rm = TRUE)
    )
  }
  conc <- dplyr::ungroup(conc)
  list(fit = fit, qp = conc)
}
